baseURL = "https://web.volf.co"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "web.volf.co"
subtitle = "i am. musing of colum mcgaley"
theme = "cactus"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
paginate = "10"

[author]
  name = "Colum McGaley"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[taxonomies]
  tag = "tags"
  category = ""  # Categories are disabled by default.

[params]
  colortheme = "dark"
  rss = true
  mathjax = true
  authorbox = true


[params.widgets]
  search = true
[[params.social]]
  name = "github"
  link = "https://github.com/volfco"
[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/company/github/"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
